version: '3'
services:
  usa:
    image: ram0987/usa:latest
    ports:
      - "85:80"
    deploy:
      replicas: 3

  india:
    image: ram0987/india:latest
    ports:
      - "86:80"
    deploy:
      replicas: 3

  japan:
    image: ram0987/japan:latest
    ports:
      - "87:80"
    deploy:
      replicas: 3

  china:
    image: ram0987/china:latest
    ports:
      - "88:80"
    deploy:
      replicas: 3
